spring:
  application:
    name: api-gateway
server:
  port: 443
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-app:8761/eureka/
spring.cloud.gateway:
  discovery:
    locator:
      enabled: true
      lower-case-service-id: true
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "http://35.175.104.155:4200"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
        allowedHeaders:
          - "*"
        allowCredentials: true
api-gateway:
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
expiration: ${expiration}
secretKey: ${secretKey}
